name = "chat-server"
main = "src/index.ts"
compatibility_date = "2024-04-05"

# Binding for D1 Database
[[d1_databases]]
binding = "DB"
database_name = "chat_db"
database_id = "cb1b852e-f451-4190-ac81-58b7e2926a25"

# Binding for Durable Objects
[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

# Binding for R2 Object Storage (Documents / Actas)
[[r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "serex-docs-prod"
